version: '3.9'
services:
  auth-service:
    env_file:
      - ../../.env.docker
    build:
      context: ../../
      dockerfile: apps/auth-service/docker/Dockerfile.dev
    container_name: auth-service
    volumes:
      - ../../apps/auth-service:/usr/src/app/apps/auth-service
      - ../../libs/backend/auth-service:/usr/src/app/libs/backend/auth-service
      - ../../libs/backend/shared:/usr/src/app/libs/backend/shared
      - ../../libs/shared:/usr/src/app/libs/shared
    restart: always
    ports:
      - ${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}