export const LOGIN_CMD = 'LOGIN';

export const UPDATE_USER_CMD = 'UPDATE_USER';
export const GET_USER_CMD = 'GET_USER';
export const FIND_USER_BY_EMAIL = 'FIND_USER_BY_EMAIL';

export const DELETE_USER_CMD = 'DELETE_USER';

export const CREATE_USER_CMD = 'CREATE_USER';

export const REGISTER_SCHOOL_CMD = 'REGISTER_SCHOOL';


export const GET_SCHOOL_CMD = 'GET_SCHOOL';
export const IS_SCHOOL_CONFIGURED_CMD = 'IS_SCHOOL_CONFIGURED';

export const REGISTER_CLASS_SCHEDULER_CMD = 'REGISTER_CLASS_SCHEDULER';

export const GET_CLASS_SCHEDULERS_CMD = 'GET_CLASS_SCHEDULERS';
export const GET_CLASS_SCHEDULER_CMD = 'GET_CLASS_SCHEDULER';

export const SHARE_CALENDAR_CMD = 'SHARE_CALENDAR';
export const GET_SHARED_CALENDAR_CMD = 'GET_SHARED_CALENDAR';
export const GET_SHARED_CALENDAR_BY_HASH_CMD = 'GET_SHARED_CALENDAR_BY_HASH';
export const TOGGLE_SHARED_CALENDAR_CMD = 'TOGGLE_SHARED_CALENDAR';
export const UPDATE_HASH_SHARED_CALENDAR_CMD = 'UPDATE_HASH_SHARED_CALENDAR';




