export const LOGIN_CMD = 'LOGIN';

export const UPDATE_USER_CMD = 'UPDATE_USER';
export const GET_USER_CMD = 'GET_USER';
export const FIND_USER_BY_EMAIL = 'FIND_USER_BY_EMAIL';

export const DELETE_USER_CMD = 'DELETE_USER';

export const CREATE_USER_CMD = 'CREATE_USER';

export const REGISTER_SCHOOL_CMD = 'REGISTER_SCHOOL';


export const GET_SCHOOL_CMD = 'GET_SCHOOL';
export const IS_SCHOOL_CONFIGURED_CMD = 'IS_SCHOOL_CONFIGURED';

export const REGISTER_CLASS_SCHEDULER_CMD = 'REGISTER_CLASS_SCHEDULER';



