version: '3.9'
services:
  auth-service:
    env_file:
      - ../../.env.docker
    build:
      context: ../../
      dockerfile: apps/auth-service/docker/Dockerfile.prod
    container_name: auth-service
    volumes:
      - auth-service-volume:/usr/src/app
    restart: always
    ports:
      - ${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}
    depends_on:
      - rabbitmq
volumes:
  auth-service-volume: