version: '3.9'
services:
  frontend:
    env_file:
      - ../../.env.docker
    build:
      context: ../
      dockerfile: apps/frontend/docker/Dockerfile.prod
    container_name: frontend 
    volumes:
      - ../../dist/apps/frontend:/usr/share/nginx/html
      - ../../apps/frontend/nginx.conf:/etc/nginx/nginx.conf 
    restart: always
    ports:
      - ${FRONTEND_PORT}:80
  api-gateway:
    env_file:
      - ../../.env.docker
    build:
      context: ../../
      dockerfile: apps/api-gateway/docker/Dockerfile.prod
    container_name: api-gateway
    volumes:
      - api-gateway-volume:/usr/src/app
    restart: always
    ports:
      - ${API_GATEWAY_PORT}:${API_GATEWAY_PORT}
    depends_on:
      - rabbitmq
  rabbitmq:
    container_name: 'rabbitmq'
    image: rabbitmq:3.8-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      # AMQP protocol port
      - '${RABBITMQ_PORT}:${RABBITMQ_PORT}'
      # HTTP management UI
      - '15672:15672'
    volumes:
      - rabbitmq-volume:/var/lib/rabbitmq
volumes:
  rabbitmq-volume:
  frontend-volume:
  api-gateway-volume:
name: campuscalendar