version: '3.9'
services:
  user-service:
    env_file:
      - ../../.env.docker
    build:
      context: ../../
      dockerfile: apps/user-service/docker/Dockerfile.prod
    container_name: user-service
    volumes:
      - user-service-volume:/usr/src/app
    restart: always
    ports:
      - ${USER_SERVICE_PORT}:${USER_SERVICE_PORT}
    depends_on:
      - user-service-db
  user-service-db:
    container_name: 'user-service-db'
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_USER=${MYSQL_USER}
    ports:
      - '${USER_SERVICE_DB_PORT}:${USER_SERVICE_DB_PORT}'
    volumes:
      - user-service-db-volume:/var/lib/mysql
volumes:
  user-service-db-volume:
  user-service-volume:
