name: Build and Push Docker

on:
  push:
    branches:
      - deployment-action

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install pnpm
      run: npm install -g pnpm@8.6.0

    - name: Install Dependencies
      run: pnpm install
    
    - name: Build all projects
      run: pnpm run build:all

    - name: Build images
      run: pnpm run build:docker

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker Images
      run: pnpm run push:docker