name: Build Affected

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup Node.js 18
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install pnpm
      run: npm install -g pnpm@8.6.0

    - name: Cache .pnpm-store
      uses: actions/cache@v2
      with:
        path: ~/.pnpm-store
        key: ${{ runner.OS }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

    - name: Install Dependencies
      run: pnpm install

    - name: Linter Affected Projects
      run: ./node_modules/.bin/nx affected:lint --base=origin/develop --head=HEAD

    - name: Build Affected Projects
      run: ./node_modules/.bin/nx affected:build --base=origin/develop --head=HEAD

    - name: Build all projects
      if: github.ref == 'refs/heads/main' 
      run: pnpm run build:all

    - name: Log in to Docker Hub
      if: github.ref == 'refs/heads/main' 
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker Images
      if: github.ref == 'refs/heads/main' 
      run: ./tools/scripts/build-push-docker.sh
